### ISSUE TITLE
Would this work in Google Cloud Run

### ISSUE THREAD

**Issue by michelsefox** [seratch/bolt-starter#18]
Hey @seratch, thank you for your Bolt templates! I had success with your GCF template, but unfortunately it bottlenecked because of so many API calls in my code. I think I would benefit from Cloud Run. Do you happen to have an example? Any help would greatly be appreciated. Thank you!

**Comment by seratch** [comment]
Hi @michelsefox, thanks for asking the question. You can check https://github.com/seratch/bolt-starter/blob/master/README_docker_ops.md#deploy-to-google-cloud-run for it!
