### ISSUE TITLE
How to run socketmode in Google Cloud Run

### ISSUE THREAD

**Issue by michelsefox** [seratch/bolt-starter#19]
Hey Seratch! 
Thank you for your very helpful docker page. The docker image built beautifully, and runs locally like a dream. I have just have one question, how may I deploy this to Google Cloud Run in socket mode. Is this possible? It runs locally, but not when I try to deploy it. Do I have to create a reverse proxy to get around the PORT issue that the service tries to listen to? Any answers or insight into this would be very much be appreciated. 

Thank you very much for your time and patience. 

Have a wonderful day!

**Comment by seratch** [comment]
It should be feasible but you may need to have an endpoint to respond for healthcheck requests. You can use customRoutes for it. https://cloud.google.com/run/docs/configuring/healthchecks

**Comment by michelsefox** [comment]
Hey Seratch,
I don't know how I would accomplish this. :) 
I've spent a few hours trying to figure it out and the only thing that succeeded was running an express server in tandem and it will deploy albeit with a huge slowdown in performance. Would customRoutes be React, Sail? 

Would it be too much trouble to provide an example? 
Happy New Year sir!

**Comment by michelsefox** [comment]
I think the compute instance would be a better option in this use case. TY @seratch !
